version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      # - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
       - docker pull vijaymateti/hugo:alpine
      # - command
  build:
    commands:
       - docker run --rm  -v $PWD:/src -u hugo vijaymateti/hugo:alpine hugo --help

  post_build:
    commands:
       - aws s3 sync --acl "public-read" --sse "AES256" public/ s3://vijaymateti.com --delete 
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths